md5: md5.ml
	ocamlfind ocamlc -package hex -package integers -linkpkg -g -o md5 md5.ml

sha: sha.ml
	ocamlfind ocamlc -package hex -package integers -linkpkg -g -o sha sha.ml

clean:
	rm *.cm* md5 sha
